//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class docentes_cursos
    {
        public int id_dictado { get; set; }
        public int id_curso { get; set; }
        public int id_docente { get; set; }
        public int cargo { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual persona persona { get; set; }
    }
}
