//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class especialidade
    {
        public especialidade()
        {
            this.planes = new HashSet<plane>();
        }
    
        public int id_especialidad { get; set; }
        public string desc_especialidad { get; set; }
    
        public virtual ICollection<plane> planes { get; set; }
    }
}
