//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public materia()
        {
            this.cursos = new HashSet<curso>();
        }
    
        public int id_materia { get; set; }
        public string desc_materia { get; set; }
        public int hs_semanales { get; set; }
        public int hs_totales { get; set; }
        public int id_plan { get; set; }
    
        public virtual ICollection<curso> cursos { get; set; }
        public virtual plane plane { get; set; }
    }
}
