//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TP2_NETEntities1 : DbContext
    {
        public TP2_NETEntities1()
            : base("name=TP2_NETEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alumnos_inscripciones> alumnos_inscripciones { get; set; }
        public DbSet<comisione> comisiones { get; set; }
        public DbSet<curso> cursos { get; set; }
        public DbSet<docentes_cursos> docentes_cursos { get; set; }
        public DbSet<especialidade> especialidades { get; set; }
        public DbSet<materia> materias { get; set; }
        public DbSet<modulo> modulos { get; set; }
        public DbSet<modulos_usuarios> modulos_usuarios { get; set; }
        public DbSet<persona> personas { get; set; }
        public DbSet<plane> planes { get; set; }
        public DbSet<usuario> usuarios { get; set; }
    }
}
