//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulos_usuarios
    {
        public int id_modulo_usuario { get; set; }
        public int id_modulo { get; set; }
        public int id_usuario { get; set; }
        public Nullable<bool> alta { get; set; }
        public Nullable<bool> baja { get; set; }
        public Nullable<bool> modificacion { get; set; }
        public Nullable<bool> consulta { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
