//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.alumnos_inscripciones = new HashSet<alumnos_inscripciones>();
            this.docentes_cursos = new HashSet<docentes_cursos>();
            this.usuarios = new HashSet<usuario>();
        }
    
        public int id_persona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public Nullable<int> legajo { get; set; }
    
        public virtual ICollection<alumnos_inscripciones> alumnos_inscripciones { get; set; }
        public virtual ICollection<docentes_cursos> docentes_cursos { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
