//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.modulos_usuarios = new HashSet<modulos_usuarios>();
        }
    
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string clave { get; set; }
        public bool habilitado { get; set; }
        public int tipo_usuario { get; set; }
        public Nullable<bool> cambia_clave { get; set; }
        public int id_persona { get; set; }
        public Nullable<int> id_plan { get; set; }
    
        public virtual ICollection<modulos_usuarios> modulos_usuarios { get; set; }
        public virtual persona persona { get; set; }
        public virtual plane plane { get; set; }
    }
}
